# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#'@export 
matMult <- function(A, B) {
    .Call('_GTV_matMult', PACKAGE = 'GTV', A, B)
}

#'@export 
matMult_sp <- function(A, B) {
    .Call('_GTV_matMult_sp', PACKAGE = 'GTV', A, B)
}

